name: Build

on:
  workflow_call:
    inputs:
      DOCKER_COMPOSE_FILES:
        required: true
        type: string
      DEPLOY_ENVIRONMENT:
        required: true
        type: string
      ENV_FILE:
        required: true
        type: string
    secrets:
      DOCKERHUB_USER:
        required: true
      DOCKERHUB_TOKEN:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.DEPLOY_ENVIRONMENT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Fetch docker cache
        uses: satackey/action-docker-layer-caching@v0.0.11
        continue-on-error: true

      - name: Build the image(s)
        run: docker compose --env-file ${{ inputs.ENV_FILE }} ${{ inputs.DOCKER_COMPOSE_FILES }} build

      - name: Log into Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push up the image(s)
        run: docker compose --env-file ${{ inputs.ENV_FILE }} ${{ inputs.DOCKER_COMPOSE_FILES }} push