name: Deploy (single container)

on:
  workflow_call:
    inputs:
      DEPLOY_ENVIRONMENT:
        required: true
        type: string
      DOCKER_COMPOSE_FILES_LIST:
        required: true
        type: string
      DOCKER_COMPOSE_PROJECT:
        required: true
        type: string
      SERVICE_NAME:
        required: true
        type: string
      DOCKER_COMPOSE_FILES:
        required: true
        type: string
    secrets:
      SSH_HOST:
        required: true
      SSH_USER:
        required: true
      SSH_KEY:
        required: true
      DEPLOY_PATH:
        required: true

jobs:
  deploy-single:
    runs-on: ubuntu-latest
    environment: ${{ inputs.DEPLOY_ENVIRONMENT }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Copy up the deployment files
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          source: ".deploy/deploy-single.sh,compose.yaml,compose.prod.yaml"
          target: ${{ secrets.DEPLOY_PATH }}

      - name: Deploy the application
        uses: appleboy/ssh-action@master
        env:
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
          DOCKER_COMPOSE_PROJECT: ${{ inputs.DOCKER_COMPOSE_PROJECT }}
          SERVICE_NAME: ${{ inputs.SERVICE_NAME }}
          DOCKER_COMPOSE_FILES: ${{ inputs.DOCKER_COMPOSE_FILES }}
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          envs: DEPLOY_PATH,DOCKER_COMPOSE_PROJECT,SERVICE_NAME
          script: |
            cd $DEPLOY_PATH
            chmod +x $DEPLOY_PATH/.deploy/deploy-single.sh
            $DEPLOY_PATH/.deploy/deploy-single.sh $DOCKER_COMPOSE_PROJECT $SERVICE_NAME "$DOCKER_COMPOSE_FILES"
